global using Ordering.API;
global using Ordering.Application;
global using Ordering.Infrastructure;
global using Ordering.Infrastructure.Data.Extenstions;
global using Carter;
global using Mapster;
global using MediatR;
global using Ordering.Application.Dtos;
global using Ordering.Application.Orders.Commands.UpdateOrder;
